# Generated by Django 3.2.5 on 2021-11-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
